# Generated by Django 5.0.6 on 2024-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehberApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoofarea',
            name='imageUrl',
            field=models.TextField(),
        ),
    ]
